namespace TryCatchFinalyApp {
    public class Program {
        static void Main() {
            //try {
            //    Person person = new Person("Test", "asd", -12);
            //}
            //catch(ArgumentException ex) {
            //    Console.WriteLine($"ArgumentException: '{ex.Message}'");
            //}
            //catch(Exception ex) {
            //    Console.WriteLine($"Error: '{ex.Message}'");
            //}


            //Console.WriteLine("Hi");
            //try {
            //    throw new Exception();
            //}
            //catch(Exception ex) {
            //    ex = null;
            //    Console.WriteLine(ex.Message);
            //}
            //finally {
            //    Console.WriteLine("Goodbye");
            //}
        }
    }
}